### ISSUE TITLE
My courses - (nearly) endless List

### ISSUE THREAD

**Issue by chrisinabztf** [dbnschools/moodle-theme_rebel#11]
I depends how someone is working with moodle - but if someone is participating in many courses, the menu-option  "My Courses" gets almost useless. Well, this is moodle standard behaviour...i think.

![myCourses](https://user-images.githubusercontent.com/50485041/102587476-2caed380-410c-11eb-9b69-8a63fb415de4.png)

Is it possible to optimize this option? Great would be:
- Predefined filter (running, past, favorites...) per user setting? 
- Or system-wide filter-setting (running, past, favorites...) in the theme?

**Comment by dbnschools** [comment]
We utilize the My Courses menu as a quick link to the most recently used courses.  It will automatically sort courses by the last access.  Thus, the courses you use the most will be the first couple you see.  Most users will not have 30 or 40 classes.  I suppose I could put a limit on the number of courses.  I haven't seen a need to do so yet.  

We will need to see what Moodle 4.0 brings us.  They are looking at all kinds of new features right in Boost.  I want to see if they write the code to use starred, last access, or other sorting method and then utilize that.  We are putting things on hold until Moodle 4.0 comes out because if it is anything like the mockups it will be a completely new way of navigating and I really like what I've seen so far.
