### ISSUE TITLE
Preset files like elearn, paper, university are missing in version 1.6

### ISSUE THREAD

**Issue by izharmail** [dbnschools/moodle-theme_rebel#2]

**Comment by dbnschools** [comment]
Yes.  We are going to focus on one major Preset in order to better support this theme long term.  You can upload the old presets on the Rebel Admin area but we will not be maintaining them.   We want this to be super simple and super easy to maintain.  We are not going to have feature bloat and include things that will break down the road.  Some of the presets broke just implementing changes in layout etc of 1.6.  Maintaining so many style options creates a maintenance nightmare.
