### ISSUE TITLE
Special Slide Icon Button

### ISSUE THREAD

**Issue by dinism** [dbnschools/moodle-theme_rebel#5]
**After setup the button**
![imagem](https://user-images.githubusercontent.com/14828021/101286557-096a5700-37e3-11eb-9879-b83ee1e2ae10.png)

**And i click, one strange symbol appears.**
![imagem](https://user-images.githubusercontent.com/14828021/101286615-6239ef80-37e3-11eb-8c59-6a7eaacf94d2.png)
**Is something i'm doing wrong?**

**I'm a PT-PT translator. 100% translated in AMOS.
Thanks for thr plugin.**

**What about this?**
![imagem](https://user-images.githubusercontent.com/14828021/101287983-a4ffc580-37eb-11eb-95e4-77dee8237974.png)

**Comment by dbnschools** [comment]
I am not sure about the first issue but the second issue is due to an error in the language string.  I will have a fix for that but in the meantime you can change this line from "theme_fordson" to theme_rebel" on your server.  
https://github.com/dbnschools/moodle-theme_rebel/blob/master/templates/teacherdash.mustache#L155

I copied the teacher dash from my other theme.

**Comment by dbnschools** [comment]
Latest revision with fix is on github now.  It will be part of the next update on Moodle.org but you can grab it now on git.
